### ISSUE TITLE
Tab的小问题

### ISSUE THREAD

**Issue by HRex39** [xiabee/MyShell#1]
Tab之后Backspace为什么不会回到原来的位置 还会把"$"给删了

**Comment by xiabee** [comment]
嗷，那个是因为解析的时候没做特殊符号处理，在程序里面认为tab是一个符号，但是在shell里占四个空格（在改了在改了.jpg

**Comment by HRex39** [comment]
> 嗷，那个是因为解析的时候没做特殊符号处理，在程序里面认为tab是一个符号，但是在shell里占四个空格（在改了在改了.jpg

控制不住想按tab自动补全的♥啊

**Comment by xiabee** [comment]
确实，，，tab补全还没做www，shell展开也还没做x

**Comment by HRex39** [comment]
> 确实，，，tab补全还没做www，shell展开也还没做x

在做了在做了.png
